### ISSUE TITLE
Not picking up on installed mods

### ISSUE THREAD

**Issue by Typhon042** [solidDoWant/Planetbase-Modpatcher#10]
I get more then one modlist, with multiple entries for this on the side, but no mods listed at all, and the mods don't work either.  Could be a issue as the game was updated after this was released, though not sure if that is the case.

**Comment by solidDoWant** [comment]
Can you please post a screenshot of the issue as well as a log? The log should be at steamapps\common\Planetbase\Planetbase_Data\output_log.txt unless the devs moved it again.
Might also be able to fix the issue by verifying the game cache and then repatching the game.

**Comment by Typhon042** [comment]
[output_log.txt](https://github.com/solidDoWant/Planetbase-Modpatcher/files/6173219/output_log.txt)
![planet001](https://user-images.githubusercontent.com/80022136/111823150-b69f5000-8938-11eb-8420-0dee9aab44a8.png)
![planet002](https://user-images.githubusercontent.com/80022136/111823167-bacb6d80-8938-11eb-9990-b24eefc8fb25.png)

**Comment by solidDoWant** [comment]
Delete your Assembly-CSharp.dll from D:\Program Files (x86)\Steam\steamapps\common\Planetbase\Planetbase_Data\Managed, verify game cache, and repatch. Should work after that. I looks like the game was patched multiple times based on the log file.

**Comment by Typhon042** [comment]
Gave that all a try, mods still not working in the game.

**Comment by solidDoWant** [comment]
Did that fix the above issue with the framework loading multiple times?
What's the full path to your mods folder?

**Comment by Typhon042** [comment]
Yea it fixed it for showing up more then once my mods folder is as follows.
C:\Users\%username%\Documents\Planetbase\Mods

**Comment by solidDoWant** [comment]
Based off of this line from the log files:

System.TypeLoadException: Could not load type 'Planetbase.IMod' from assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.

The mods you are trying to load are not compatible with the framework and are probably for another mod loader. Mods that are compatible with this launcher must extend PlanetbaseFramework.ModBase. I'm guessing these mods are built for the old modding system build by jpfarias.

**Comment by NeoRider7** [comment]
> The mods you are trying to load are not compatible with the framework and are probably for another mod loader. 
Mods that are compatible with this launcher must extend PlanetbaseFramework.ModBase. 
I'm guessing these mods are built for the old modding system build by jpfarias.

Guys, I did not quite understand what you wrote. 
Please tell me, are [Patcher-2](https://www.nexusmods.com/planetbase/mods/35) and mods working now or not?
And if the mods work, then which ones.
For example, do [mods created by JPFarias](https://www.nexusmods.com/users/19987409?tab=user+files) work with [Patcher-2](https://www.nexusmods.com/planetbase/mods/35)? 

**_If there are mods that work with Patcher-2, can you please send a link to these mods?_**
Perhaps there are such mods on [NexusMods](https://www.nexusmods.com/planetbase/mods/).

But now on NexusMods I see two types of mods:
1) Mods for [Patcher-1](https://www.nexusmods.com/planetbase/mods/1) which were created by [JPFarias](https://www.nexusmods.com/planetbase/users/19987409?tab=user+files).
2) Mods for "[Unity Mod Manager Configuration](https://www.nexusmods.com/planetbase/mods/43)" which were created by [Tahvohck](https://github.com/Tahvohck/Planetbase-Mods).
I did not find mods for [Patcher-2](https://www.nexusmods.com/planetbase/mods/35?tab=description) on the [NexusMods](https://www.nexusmods.com/planetbase/mods/) website.

**Comment by solidDoWant** [comment]
@NeoRider7 Please keep your question to your [issue here](https://github.com/solidDoWant/Planetbase-Framework/issues/13). Asking it multiple times does not add to the discussion and detracts from other issues.
