### ISSUE TITLE
Compatibility with 1.2.1

### ISSUE THREAD

**Issue by bradyemerson** [solidDoWant/Planetbase-Modpatcher#2]
Any plans to update the patcher to be compatible with version 1.2.1? I tried patching with the latest 2.0.0 patcher version and got a startup error.

**Comment by solidDoWant** [comment]
Unfortunately the patcher isn't compiling/running correctly except in my dev environment. Message me on steam and I'll send you a patched binary.

**Comment by bradyemerson** [comment]
@solidDoWant , thanks for the offer, but I can't find you on steam. Do you have the same username there?

**Comment by solidDoWant** [comment]
Whoops, I thought I had it linked on here. My profile is here: http://steamcommunity.com/id/TheiInTEAM/

**Comment by solidDoWant** [comment]
Fixed all these issues in the latest commit
