### ISSUE TITLE
Help with modding

### ISSUE THREAD

**Issue by SpawnofWar** [solidDoWant/Planetbase-Modpatcher#3]
Hi,
I've download the code/files you have here. I however am unable to find an exe file or any other file that would allow me to start the info you have in those files. Is there a tutorial or could you explain how to start the mod/allow me to play the mods already created? Thanks.

**Comment by solidDoWant** [comment]
See the documentation https://github.com/solidDoWant/Planetbase-XMLModloaderMod/wiki or https://github.com/solidDoWant/Planetbase-Framework/wiki. Documentation will be available within a few hours of this post.
