### ISSUE TITLE
Patching breaks game

### ISSUE THREAD

**Issue by SilverlightPony** [solidDoWant/Planetbase-Modpatcher#6]
Game will not load/start after being patched.

Clean install of game works fine.

Run patcher, then try to launch game.  Game window appears, but remains black; no Madruga logo or main menu appears.

Restore Assembly-CSharp.dll backup.  Game works fine again.

**Comment by solidDoWant** [comment]
Log file? Did you install the framework, or just patch it?

**Comment by solidDoWant** [comment]
No input from user. Closing ticket.
