### ISSUE TITLE
enum member access level modified after patching Assebly-CSharp.dll with ModPatcher v2.2

### ISSUE THREAD

**Issue by CJ-Abrams** [solidDoWant/Planetbase-Modpatcher#9]
Hi s.D.W.

While attempting to port a Planetbase Mod from PBFramework 2.1.2 to latest Framework version, I've noticed that in lib. Assembly-CSharp.dll, enum. 'Mode' of class 'GameStateGame' has changed its acces level from 'public' (default value with ModPatch v2.1 applied) to 'private' after applying ModPatch v2.2.
Of course its enum members value can still be retrieved via Introspection, but if that was an unexpected modification, it could return to be a public class member?
It would be much better.

Thanks for your time

@CJ-Abrams

**Comment by solidDoWant** [comment]
You're absolutely right. I'll work on fixing this.

**Comment by solidDoWant** [comment]
This should be fixed in the latest commit. This will be published with the next release.
